server:
  servlet:
    context-path:
  port: 8080
  session-timeout: 30
  uri-encoding: UTF-8


logging:
  config: classpath:log/log4j2.xml

#jasypt加密的密匙,生产环境用命令传参设置
jasypt:
  encryptor:
    password: 61EC6F20F7EEA88036505D887AF14BAB

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/witter?serverTimezone=UTC&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      hikariz:
        maximum-pool-size: 5
        auto-commit: false
        idle-timeout: 30000
        pool-name: HikariConnectionPool
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: "SELECT 1"
    secondary:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: ENC(xRnehQLt8IfrBaK5W+KeeWm4ZmkNM3vVlYp8u70g7ZuAjndMjZFonfp3+JD4LcbKBYd8DrhuMIj6Hj2zALTcYOczdWMF+QItNr5LaGBCraQ=)
      username: ENC(Cn645EeW/xbh2KvWoCFjbBUHrYNdEt0D) # User
      password: ENC(r8QNIUmOGQ9vag8z/6AvIQ==) # PWD
      hikariz:
        maximum-pool-size: 5
        auto-commit: false
        idle-timeout: 30000
        pool-name: HikariConnectionPool
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: "SELECT 1"



mybatis:
  mapper-locations: "classpath:mapper/*"
  type-aliases-package: com.tipo.witter.pojo
  configuration:
    map-underscore-to-camel-case: true



